# Define the types Tezos of nodes we want to deploy in our cluster
nodes:
  rolling-node:
    storage_size: 100Gi
    # We create a new k8s storage class in the Pulumi index.ts file that allows
    # us to expand an EBS volume's size. The default gp2 storage class created
    # by EKS does not allow for volume expansion. We tell our `rolling-nodes` to
    # use this storage class.
    storageClassName: "gp3"
    # Run the Octez implementation of Tezos node.
    runs:
      - octez_node
    # Create 2 Tezos rolling nodes that will be distributed across the 2 cluster
    # EC2 nodes we will be deploying.
    instances:
      - config:
          shell:
            history_mode: rolling
      - config:
          shell:
            history_mode: rolling

# Have the nodes download and use a tarball of a mainnet rolling node
# filesystem. This allows the nodes to sync much faster with the head of the
# chain than if they started from the genesis block. By default, tezos-k8s will
# download and unpack a Tezos native snapshot. A tarball is a LZ4-compressed
# filesystem tar of a node's data directory. It is faster to download and
# bootstrap the node. https://xtz-shots.io/ is the default source of the tar.
prefer_tarballs: true
